language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"
notifications:
  irc:
    channels:
        - "chat.freenode.net#dokuwiki"
    on_success: change
    on_failure: change
script: cd _test && phpunit --verbose --stderr
